export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const GET_MUSIC_ITEMS = 'GET_MUSIC_ITEMS';
export const GET_MUSIC_ITEMS_FAIL = 'GET_MUSIC_ITEMS_FAIL'
export const ITEMS_LOADING = 'ITEMS_LOADING';

export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';

export const GET_FAVORITE_MUSIC_LIST_SUCCESS = 'GET_FAVORITE_MUSIC_LIST_SUCCESS';
export const GET_FAVORITE_MUSIC_LIST_LOADED = 'GET_FAVORITE_MUSIC_LIST_LOADED';
export const GET_FAVORITE_MUSIC_LIST_FAIL = 'GET_FAVORITE_MUSIC_LIST_FAIL';

export const ADD_TO_FAVORITE_LIST_SUCCESS = 'ADD_TO_FAVORITE_LIST_SUCCESS';
export const ADD_TO_FAVORITE_LIST_FAIL = 'ADD_TO_FAVORITE_LIST_FAIL';

export const DELETE_TO_FAVORITE_LIST_SUCCESS = 'DELETE_TO_FAVORITE_LIST_SUCCESS';
export const DELETE_TO_FAVORITE_LIST_FAIL = 'DELETE_TO_FAVORITE_LIST_FAIL';

export const CONTACT_ADMIN_SUCCESS = 'CONTACT_ADMIN_SUCCESS';
export const CONTACT_ADMIN_FAIL = 'CONTACT_ADMIN_FAIL';

export const MODIFY_USERNAME_SUCCESS = 'MODIFY_USERNAME_SUCCESS';
export const MODIFY_USERNAME_FAIL = 'MODIFY_USERNAME_FAIL';

export const MODIFY_MAIL_CONTACT_SUCCESS = 'MODIFY_MAIL_CONTACT_SUCCESS';
export const MODIFY_MAIL_CONTACT_FAIL = 'MODIFY_MAIL_CONTACT_FAIL';

export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL';

export const MODIFY_PASSWORD_SUCCESS = 'MODIFY_PASSWORD_SUCCESS';
export const MODIFY_PASSWORD_FAIL = 'MODIFY_PASSWORD_FAIL';

export const DELETE_USER_ACCOUNT_SUCCESS = 'DELETE_USER_ACCOUNT_SUCCESS';
export const DELETE_USER_ACCOUNT_FAIL = 'DELETE_USER_ACCOUNT_FAIL';

export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const GET_SUCCESS = 'GET_SUCCESS';
export const CLEAR_SUCCESSS = 'CLEAR_SUCCESS';

export const IS_ADMIN = 'IS_ADMIN';
export const NOT_ADMIN = 'NOT_ADMIN';

export const ADD_CONTENT_SUCCESS = 'ADD_CONTENT_SUCCESS';
export const ADD_CONTENT_FAIL = 'ADD_CONTENT_FAIL';

export const DELETE_CONTENT_SUCCESS = 'DELETE_CONTENT_SUCCESS';
export const DELETE_CONTENT_FAIL = 'DELETE_CONTENT_FAIL';

export const  LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const PLAYER_LOADING = 'PLAYER_LOADING';
export const PLAYER_LOADED = 'PLAYER_LOADED';
export const PLAYER_ON_PLAY = 'PLAYER_ON_PLAY';
export const PLAYER_ON_PAUSE = 'PLAYER_ON_PAUSE';
export const PLAYER_PLAY_NEXT = 'PLAYER_PLAY_NEXT';
export const PLAYER_PLAY_PREVIOUS = 'PLAYER_PLAY_PREVIOUS';
export const PLAYER_ON_STOP = 'PLAYER_ON_STOP';
export const PLAYER_UNLOAD = 'PLAYER_UNLOAD';

export const ON_REDIRECTION = 'ON_REDIRECTION';
export const REDIRECTED = 'REDIRECTED';